package zw.shallom.service;
import zw.shallom.model.*;import zw.shallom.exception.*;import zw.shallom.repository.FileStore;import java.io.IOException;import java.util.*;import java.util.stream.Collectors;
/** Business rules and demo school data, shared by all HTTP requests. */
public class SchoolService {
 public static final String[] SUBJECTS={"Accounts","Agriculture","Biology","Chemistry","Computer Science","English Language","Fashion & Fabrics","Geography","History","Mathematics","Physics","Shona","Food Technology","Literature","Commerce"};
 public static final String[][] SPORTS={{"Athletics","Monday"},{"Basketball","Tuesday"},{"Chess","Wednesday"},{"Football","Thursday"},{"Netball","Tuesday"},{"Rugby","Friday"},{"Swimming","Wednesday"},{"Tennis","Thursday"},{"Volleyball","Monday"},{"Cricket","Friday"}};
 public static final String[][] CLASSES={{"Form 1A","Mrs Moyo"},{"Form 1B","Mr Ncube"},{"Form 2A","Mrs Dube"},{"Form 2B","Mr Sibanda"},{"Form 3A","Mrs Moyo"},{"Form 3B","Mr Ncube"},{"Form 4","Mr Dube"},{"Lower 6","Mrs Sibanda"},{"Upper 6","Mr Moyo"}};
 private final FileStore store;private final Map<String,User> users=new LinkedHashMap<String,User>();
 public SchoolService(String path){store=new FileStore(path);seedUsers();if(store.read("results.dat").isEmpty())try{store.write("results.dat",Arrays.asList(new Result("student1","Mathematics",78,"teacher1"),new Result("student1","English Language",82,"teacher2"),new Result("student2","Biology",67,"teacher1")));}catch(IOException ignored){}}
 private void seedUsers(){add("student1","pass123","Tadiwa Moyo","Form 4",Role.STUDENT);add("student2","pass123","Rudo Ncube","Form 3A",Role.STUDENT);add("teacher1","teach123","Mr Tendai Dube","Form 4",Role.TEACHER);add("teacher2","teach123","Mrs Nyasha Moyo","Form 3A",Role.TEACHER);add("ancil1","ancil123","Simon Ncube","",Role.ANCILLARY);add("ancil2","ancil123","Grace Dube","",Role.ANCILLARY);add("deputy","dep123","Deputy Headmaster","",Role.DEPUTY);add("headmaster","head123","Headmaster","",Role.HEADMASTER);}
 private void add(String u,String p,String n,String c,Role r){users.put(u,new User(u,p,n,c,r));}
 public User authenticate(String u,String p)throws InvalidLoginException{User x=users.get(u);if(x==null||!x.getPassword().equals(p))throw new InvalidLoginException("Incorrect username or password.");return x;}
 public synchronized Payment pay(User user,String id,double amount,String method)throws PaymentException{if(user.getRole()!=Role.STUDENT)throw new PaymentException("Only students can submit fee payments.");if(amount<=0||amount>1000000)throw new PaymentException("Enter an amount greater than zero.");if(!Arrays.asList("EcoCash","Bank Transfer","Cash","Swipe","ZIPIT").contains(method))throw new PaymentException("Choose a valid payment method.");Payment p=new Payment("SHS-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(),user.getName(),id,amount,method);List<Payment> all=store.read("payments.dat");all.add(p);try{store.write("payments.dat",all);}catch(IOException e){throw new PaymentException("Could not save payment. Please try again.");}return p;}
 public synchronized void addResult(String student,String subject,int mark,String teacher)throws IOException{List<Result> all=store.read("results.dat");all.add(new Result(student,subject,mark,teacher));store.write("results.dat",all);}
 public synchronized void addIssue(String reporter,String description)throws IOException{List<Issue> all=store.read("issues.dat");all.add(new Issue(reporter,description));store.write("issues.dat",all);}
 public List<Payment> payments(){return store.read("payments.dat");}public List<Result> results(){return store.read("results.dat");}public List<Issue> issues(){return store.read("issues.dat");}
 public List<Payment> history(String username){return payments().stream().filter(p->p.getStudentId().equals(username)).sorted(Comparator.comparing(Payment::getTimestamp).reversed()).collect(Collectors.toList());}
 public Map<String,User> users(){return Collections.unmodifiableMap(users);}public int totalTeachers(){return (int)users.values().stream().filter(u->u.getRole()==Role.TEACHER).count();}public double totalCollected(){return payments().stream().mapToDouble(Payment::getAmount).sum();}
 public synchronized void report()throws IOException{List<Payment> ps=payments();try(java.io.PrintWriter w=new java.io.PrintWriter(new java.io.FileWriter(storePath()+"/payments_report.txt"))){ps.stream().sorted(Comparator.comparing(Payment::getTimestamp)).forEach(p->w.println(p.getReference()+" | "+p.getStudent()+" | "+p.getAmount()));}}
 private String storePath(){return System.getProperty("shallom.data", "data");}
}
